// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytjjvoumwdaukygryzjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0amp2b3Vtd2RhdWt5Z3J5empqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzcyMTEsImV4cCI6MjA1OTY1MzIxMX0.AV2vaI7iZjC-LseQr_j61sRtAAhiiZ7eOmIlCUil2hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);